### PR TITLE
Output sshd logs to a file

### PR DESCRIPTION
**Pull request by DeviaVir**
Instead of echo'ing all failed ssh login attempts and therefore filling the only log, send these logs to a different file which can be mounted like `git-deploy-sshd.log:/var/log/secure` and rotated on the host machine at will.

Normal git-deploy operational logs will still be outputted.

@pebble/webops

### CODE REVIEW

**Comment by thepwagner** [comment]
How do permissions work? I'm reading file gets created by `root` but `git` needs to append it?

**Comment by thepwagner** [comment]
+1, maybe declare as `VOLUME` to drive the pattern home? (confused me until I saw related bits).

**Comment by DeviaVir** [comment]
@thepwagner Not entirely sure this works as I hope; docs say it should work though

**Comment by thepwagner** [comment]
+1

**Comment by thepwagner** [comment]
I'm getting:
```
Step 26 : VOLUME /var/log/secure
cannot mount volume over existing file, file exists /mnt/sda1/var/lib/docker/aufs/mnt/95ee9935357453c71e9a49e4139200008d01186f1b2787dbd340dca53918a043/var/log/secure
```

during the build (via bats).

**Comment by DeviaVir** [comment]
@thepwagner w00t, now with CI! I also took out the `VOLUME` and went with the documentation path, as it is a fix that only applies to certain (a bit more public) servers I don't want to force this pattern.

**Comment by thepwagner** [comment]
+1

**Comment by DeviaVir** [comment]
Merging because it's harmless and adds CI _now_

**Pull request merged**
