### PR TITLE
Restore OSX support to Makefile

### PR DESCRIPTION
**Pull request by thepwagner**
https://github.com/bsideup/forward2docker looks interesting for OSX
folks too; but requires more boat rocking.

### CODE REVIEW

**Comment by lrvick** [comment]
Fails on Arch with environment passed that way:

```
 ✗ Can backup and restore a repository
   (from function `ssh_command' in file test/test_helper.bash, line 115,
    in test file test/test.bats, line 21)
     `ssh_command "mkrepo testrepo"' failed with status 255
   f263927419f827583c86c8d06a53e655cfcfde44f5ce63516bb8eac56e1e5a14
   ssh: Could not resolve hostname "localhost": Name or service not known
```

Added patch which fixes for me. May or may not break OSX again...

**Comment by DeviaVir** [comment]
@lrvick `ssh: Could not resolve hostname "localhost": Name or service not known` that reads like your localhost has issues?

**Comment by lrvick** [comment]
When I hard-code to localhost, as it was before, it works fine. Could be quoting weirdness...

**Comment by DeviaVir** [comment]
@lrvick Can you test again? (after pulling in changes)

**Comment by thepwagner** [comment]
Doh; I tested the right DOCKER_HOST_IP get set on Arch but didn't want to install `bash-bats` to actually dig into the suite.

Working for me without quotes

```
which: no docker-machine in (/home/pwagner/bin:/home/pwagner/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)
docker build -t pebble/test-git-deploy .
Sending build context to Docker daemon  1.03 MB
Step 1 : FROM debian:jessie
...
Successfully built 2c6e31d00f9f
 ✓ Can build container
   Can backup and restore a repository  
```

**Pull request merged**
