### PR TITLE
add procmail for 'lockfile' and other useful shell commands

### PR DESCRIPTION
**Pull request by lrvick**

### CODE REVIEW

**Comment by DeviaVir** [comment]
👍; difference is +5MB, is that worth it? it's already a huge container so am leaning to say "okay sure"
latest build seems to have failed: https://hub.docker.com/r/pebbletech/git-deploy/builds/bknklu4tt3gn2btqnrfpf7f/ (but looks intermittent)

**Comment by thepwagner** [comment]
+1.
Could maybe skirt the 5MB tax by using `flock` like https://github.com/pebble/git-deploy/blob/master/base-hooks/pre-receive#L50 ?

**Comment by thepwagner** [comment]
Re: build failure.
I'm ready to give up on httpredir too (iirc I was the hold out). It _should_ be the best, but it keeps serving flaky mirrors.

`Fetching mea-culpa-1.0.0.deb failed: Connection Reset`

**Comment by lrvick** [comment]
@thepwagner I would need a way to use flock in such a way that it can exit 0 or 1 if it does or does not get a lock like lockfile can (or via a function wrapper) because I intend to use this to take and release -multiple- locks vs just one, which is all the current flock pattern allows for. 

Will merge to get lockfile for now, but if we find a ligther replacement for the same use case we can always remove lockfile later in favor of that.

**Pull request merged**
