### PR TITLE
PBL-21842: Provide encryption of environment variables

### PR DESCRIPTION
**Pull request by thepwagner**
A common git-deploy pattern involves .env files that propogate through
etcd to environment variables for the target service.
If this pattern is used for passwords, it leaves a plaintext copy:
- in the git-deploy container
- in any clones of git-deploy repo/history
- in etcd (the scariest!)

This changeset introduces a new git-shell command: secret.
The new command generates a ciphertext that can be committed to git
in place of the original plaintext string.
This prevents plaintext storage in all of the above cases.

Presently all keys stay in the git-deploy container: export
and propagation are left as an exercise for downstream.
Eventually these could go be stored in etcd, but we need to
enable+trust etcd authentication before that becomes sane.

### CODE REVIEW

**Comment by thepwagner** [comment]
@lrvick review?

**Comment by lrvick** [comment]
Super solid work, and excellent testing.

Some thoughts though.

Etcd is relevant to our use case at Pebble, but we should not assume in comments/docs that etcd is what others who might implement git-deploy want to use. (Though this is fine in tests and examples). We ourselves may not want to use Etcd, or only Etcd in the future.

Perhaps the scope of git-deploy should perhaps be limited to providing very generic tools with few infrastructure assumptions. A container with git repos, simple hook management, encrypted backups, and a mechanism for encrypting sensitive contents as desired. Anything beyond these core things (which kind of -need- to be at the git-deploy level) should be a concern of environment-specific hooks.

Also so far nothing in git-deploy itself (outside of examples) assumes a user is going to have > 1 app, or that they will use apps/* etc. If someone wants to use a Terraform folder layout, or Ansible conventions, etc, we should not have anything that gets in the way of that.

It is possible as well one might need to store infrastructure specific secrets that get used by specialized hooks and external deploy tools such as a Docker registry, SSL certs, etc that don't relate to a particular app.

Considering the above, perhaps ```secret``` should be adjusted to not care about apps at all, and instead be limited to a friendly wrapper for gpg that simply generates bare gpg encrypted and armored strings against any named key and helpfully generates keys that don't yet exist.

Perhaps then the CLI is just: ```secret KEY_NAME somevalue```

Thoughts?

**Comment by thepwagner** [comment]
Agreed that coupling to the apps/* hierarchy stinks. My thinking in validating <app_name> vs apps/* was to minimize cruft caused by a fat finger: if 99% of my keys are encrypted with "foo-bar" but I enter "foobar" in a rushed upgrade, I'd rather get a warning/error than a clean response to bite me later when it fails to decrypt.
If keys are just names (they should be, I like that), I think an explicit "create a key" operation mitigates that.


I liked the idea of signing ciphertexts with a repo-level key for its ability to prevent injection. I've been assuming git-deploy will export+purge encryption private keys, leaving encryption keys "near" the service whose secrets they are protecting (i.e. parent host or a sibling container). If an app is compromised, AND pivoted to the encryption key, an attacker can't set OAUTH_CALLBACK=http://malicious.com/proxy without also owning git-deploy.
This is a pretty weak last line of defence, but sounded good on paper while spec-ing this out. Kill.


I still like incorporating the KEY=${KEY} header to prevent swapping ciphertexts: I compromise an app, discover the config backend (i.e. etcd) and copy the value for DATABASE_PASSWORD to something exposed/logged by the app like (i.e. LISTEN_ADDRESS/PORT, VERSION, etc). Now I just need to trigger a restart (DoS) and the app will start spilling its beans. All from the comfort of HTTP.
That said, the KEY=${KEY} tier _can_ be implemented in downstream hooks. Blame Python for encouraging me to ship "batteries".


I think that leaves us with:
```
secret FOO bar # error "key does not exist"
genkey FOO
genkey FOO # error "key already exists"
secret FOO bar
cat binary.dat | secret FOO
```

And for paranoid users using a key value store like etcd:
```
genkey FOO
secret FOO DB_PASSWORD=s3cret # embed storage location, git-deploy don't care
# verify+trimming storage location left for downstream
```

**Comment by thepwagner** [comment]
@lrvick second commit affords API discussed

**Comment by lrvick** [comment]
Sad to see the etcd/app container testing setup go. That was a clever. Can potentially re-use some of that in hook testing.

All LGTM

+1

**Pull request merged**
